{{- if and (not .Values.database.existingSecret) .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "niks3.dbSecretName" . }}
  labels: {{- include "niks3.labels" . | nindent 4 }}
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url | quote }}
{{- end }}
{{- if and (not .Values.auth.existingSecret) .Values.auth.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "niks3.tokenSecretName" . }}
  labels: {{- include "niks3.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
{{- if and (not .Values.s3.useIAM) (not .Values.s3.existingSecret) .Values.s3.accessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "niks3.s3SecretName" . }}
  labels: {{- include "niks3.labels" . | nindent 4 }}
stringData:
  access-key: {{ .Values.s3.accessKey | quote }}
  secret-key: {{ .Values.s3.secretKey | quote }}
{{- end }}
{{- with include "niks3.oidcProviders" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "niks3.fullname" $ }}-oidc
  labels: {{- include "niks3.labels" $ | nindent 4 }}
data:
  oidc.json: {{ . | quote }}
{{- end }}
