linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - funlen
    - godox
    - gomnd
    - mnd
    - varnamelen
linters-settings:
  tagliatelle:
    # Check the struct tag name case.
    case:
      rules:
        json: snake
