linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref
    - funlen
    - godox
    - varnamelen
    - gocognit
    - cyclop
    - err113
    - gomnd
    - execinquery
linters-settings:
  tagliatelle:
    # Check the struct tag name case.
    case:
      rules:
        json: snake
