// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Closure struct {
	NarHash   string           `json:"nar_hash"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ClosureObject struct {
	ClosureNarHash string `json:"closure_nar_hash"`
	NarHash        string `json:"nar_hash"`
}

type Object struct {
	NarHash        string `json:"nar_hash"`
	ReferenceCount int32  `json:"reference_count"`
}

type Upload struct {
	ID             int64            `json:"id"`
	StartedAt      pgtype.Timestamp `json:"started_at"`
	ClosureNarHash string           `json:"closure_nar_hash"`
}
