// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Closure struct {
	Key       string           `json:"key"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type MultipartUpload struct {
	PendingClosureID int64  `json:"pending_closure_id"`
	ObjectKey        string `json:"object_key"`
	UploadID         string `json:"upload_id"`
}

type Object struct {
	Key            string           `json:"key"`
	Refs           []string         `json:"refs"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	FirstDeletedAt pgtype.Timestamp `json:"first_deleted_at"`
}

type PendingClosure struct {
	ID        int64            `json:"id"`
	Key       string           `json:"key"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}

type PendingObject struct {
	PendingClosureID int64    `json:"pending_closure_id"`
	Key              string   `json:"key"`
	Refs             []string `json:"refs"`
}
