// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupPendingClosures = `-- name: CleanupPendingClosures :execrows
WITH cutoff_time AS (
    SELECT timezone('UTC', now()) - interval '1 second' * $1::int AS time
),

old_closures AS (
    SELECT id
    FROM pending_closures, cutoff_time
    WHERE started_at < cutoff_time.time
),

inserted_objects AS (
    INSERT INTO objects (key, refs, deleted_at)
    SELECT
        po.key,
        po.refs,
        timezone('UTC', now())
    FROM pending_objects AS po
    JOIN old_closures oc ON po.pending_closure_id = oc.id
    ON CONFLICT (key) DO NOTHING
    RETURNING key
),

deleted_pending_objects AS (
    DELETE FROM pending_objects
    USING old_closures
    WHERE pending_objects.pending_closure_id = old_closures.id
    RETURNING pending_closure_id
)

DELETE FROM pending_closures
USING old_closures
WHERE pending_closures.id = old_closures.id
`

// Whatever an abandoned upload left in S3 becomes a tombstone so the reaper
// removes it after the normal grace period.
// Delete pending objects that were inserted into the objects table
// Delete pending closures older than the specified interval
// This will cascade to pending_objects
func (q *Queries) CleanupPendingClosures(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupPendingClosures, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const commitPendingClosure = `-- name: CommitPendingClosure :exec
SELECT commit_pending_closure($1::bigint)
`

func (q *Queries) CommitPendingClosure(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, commitPendingClosure, dollar_1)
	return err
}

const countPendingClosures = `-- name: CountPendingClosures :one
SELECT count(*) FROM pending_closures
`

func (q *Queries) CountPendingClosures(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingClosures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteClosures = `-- name: DeleteClosures :execrows
DELETE FROM closures
WHERE closures.updated_at < $1
  AND closures.key NOT IN (SELECT narinfo_key FROM pins)
`

// Delete old closures, but exclude any that are pinned
func (q *Queries) DeleteClosures(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClosures, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMultipartUpload = `-- name: DeleteMultipartUpload :exec
DELETE FROM multipart_uploads
WHERE upload_id = $1
`

func (q *Queries) DeleteMultipartUpload(ctx context.Context, uploadID string) error {
	_, err := q.db.Exec(ctx, deleteMultipartUpload, uploadID)
	return err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM pins
WHERE name = $1
`

func (q *Queries) DeletePin(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deletePin, name)
	return err
}

const deleteTombstonedObjects = `-- name: DeleteTombstonedObjects :execrows
DELETE FROM objects
WHERE key = any($1::varchar []) AND deleted_at IS NOT NULL
`

func (q *Queries) DeleteTombstonedObjects(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTombstonedObjects, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClosure = `-- name: GetClosure :one
SELECT updated_at FROM closures
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetClosure(ctx context.Context, key string) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getClosure, key)
	var updated_at pgtype.Timestamp
	err := row.Scan(&updated_at)
	return updated_at, err
}

const getClosureForShare = `-- name: GetClosureForShare :one
SELECT updated_at FROM closures
WHERE key = $1 LIMIT 1
FOR SHARE
`

// Lock the closure row so concurrent GC cannot delete it between the
// existence check and the pin upsert.
func (q *Queries) GetClosureForShare(ctx context.Context, key string) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getClosureForShare, key)
	var updated_at pgtype.Timestamp
	err := row.Scan(&updated_at)
	return updated_at, err
}

const getClosureObjects = `-- name: GetClosureObjects :many
WITH RECURSIVE closure_reach AS (
    -- Start with the provided closure key
    SELECT o.key, o.refs 
    FROM objects o
    WHERE o.key = $1
    UNION
    -- Recursively add all referenced objects
    SELECT o.key, o.refs 
    FROM objects o
    INNER JOIN closure_reach cr ON o.key = ANY(cr.refs)
)
SELECT DISTINCT key FROM closure_reach
`

// Return objects reachable from the given closure key
func (q *Queries) GetClosureObjects(ctx context.Context, key string) ([]string, error) {
	rows, err := q.db.Query(ctx, getClosureObjects, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveObjects = `-- name: GetLiveObjects :many
WITH locked AS (
    SELECT key, deleted_at FROM objects
    WHERE key = any($1::varchar [])
    FOR SHARE
)

SELECT key FROM locked WHERE deleted_at IS NULL
`

// Must run after the caller's pending_objects rows are committed. FOR SHARE
// blocks on rows the GC reaper currently holds, so once this returns any
// reaper batch touching these keys has finished and later batches will see
// the pending rows and skip them. Tombstoned rows are locked too but not
// returned: their S3 object may already be gone, so the client re-uploads.
func (q *Queries) GetLiveObjects(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getLiveObjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMultipartUpload = `-- name: GetMultipartUpload :one
SELECT pending_closure_id, object_key, upload_id
FROM multipart_uploads
WHERE upload_id = $1 AND object_key = $2
`

type GetMultipartUploadParams struct {
	UploadID  string `json:"upload_id"`
	ObjectKey string `json:"object_key"`
}

func (q *Queries) GetMultipartUpload(ctx context.Context, arg GetMultipartUploadParams) (MultipartUpload, error) {
	row := q.db.QueryRow(ctx, getMultipartUpload, arg.UploadID, arg.ObjectKey)
	var i MultipartUpload
	err := row.Scan(&i.PendingClosureID, &i.ObjectKey, &i.UploadID)
	return i, err
}

const getObjectStats = `-- name: GetObjectStats :one
SELECT object_count, total_bytes FROM object_stats WHERE id
`

type GetObjectStatsRow struct {
	ObjectCount int64 `json:"object_count"`
	TotalBytes  int64 `json:"total_bytes"`
}

func (q *Queries) GetObjectStats(ctx context.Context) (GetObjectStatsRow, error) {
	row := q.db.QueryRow(ctx, getObjectStats)
	var i GetObjectStatsRow
	err := row.Scan(&i.ObjectCount, &i.TotalBytes)
	return i, err
}

const getOldMultipartUploads = `-- name: GetOldMultipartUploads :many
SELECT upload_id, object_key
FROM multipart_uploads mu
JOIN pending_closures pc ON mu.pending_closure_id = pc.id
WHERE pc.started_at < timezone('UTC', now()) - interval '1 second' * $1::int
`

type GetOldMultipartUploadsRow struct {
	UploadID  string `json:"upload_id"`
	ObjectKey string `json:"object_key"`
}

func (q *Queries) GetOldMultipartUploads(ctx context.Context, dollar_1 int32) ([]GetOldMultipartUploadsRow, error) {
	rows, err := q.db.Query(ctx, getOldMultipartUploads, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOldMultipartUploadsRow
	for rows.Next() {
		var i GetOldMultipartUploadsRow
		if err := rows.Scan(&i.UploadID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingKeysAmong = `-- name: GetPendingKeysAmong :many
SELECT DISTINCT key FROM pending_objects
WHERE key = any($1::varchar [])
`

// Second check with a fresh snapshot after LockObjectsForDeletion took its
// row locks: catches pending rows committed while the first statement ran.
func (q *Queries) GetPendingKeysAmong(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPendingKeysAmong, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingObject = `-- name: GetPendingObject :one
SELECT refs, size FROM pending_objects
WHERE pending_closure_id = $1 AND key = $2
`

type GetPendingObjectParams struct {
	PendingClosureID int64  `json:"pending_closure_id"`
	Key              string `json:"key"`
}

type GetPendingObjectRow struct {
	Refs []string    `json:"refs"`
	Size pgtype.Int8 `json:"size"`
}

func (q *Queries) GetPendingObject(ctx context.Context, arg GetPendingObjectParams) (GetPendingObjectRow, error) {
	row := q.db.QueryRow(ctx, getPendingObject, arg.PendingClosureID, arg.Key)
	var i GetPendingObjectRow
	err := row.Scan(&i.Refs, &i.Size)
	return i, err
}

const getPendingObjectByKey = `-- name: GetPendingObjectByKey :one
SELECT refs, size FROM pending_objects
WHERE key = $1
LIMIT 1
`

type GetPendingObjectByKeyRow struct {
	Refs []string    `json:"refs"`
	Size pgtype.Int8 `json:"size"`
}

// Any pending closure's row for this key; used to recover refs/size when the
// upload is registered outside closure commit.
func (q *Queries) GetPendingObjectByKey(ctx context.Context, key string) (GetPendingObjectByKeyRow, error) {
	row := q.db.QueryRow(ctx, getPendingObjectByKey, key)
	var i GetPendingObjectByKeyRow
	err := row.Scan(&i.Refs, &i.Size)
	return i, err
}

const getPendingObjectKeys = `-- name: GetPendingObjectKeys :many
SELECT key FROM pending_objects
WHERE pending_closure_id = $1
`

func (q *Queries) GetPendingObjectKeys(ctx context.Context, pendingClosureID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getPendingObjectKeys, pendingClosureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPin = `-- name: GetPin :one
SELECT name, narinfo_key, store_path, created_at, updated_at
FROM pins
WHERE name = $1
`

func (q *Queries) GetPin(ctx context.Context, name string) (Pin, error) {
	row := q.db.QueryRow(ctx, getPin, name)
	var i Pin
	err := row.Scan(
		&i.Name,
		&i.NarinfoKey,
		&i.StorePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedundantMultipartUploads = `-- name: GetRedundantMultipartUploads :many
SELECT upload_id
FROM multipart_uploads
WHERE object_key = $1 AND upload_id <> $2
`

type GetRedundantMultipartUploadsParams struct {
	ObjectKey string `json:"object_key"`
	UploadID  string `json:"upload_id"`
}

// Upload IDs other pending_closures opened for object_key, used to abort
// duplicates once one upload of the NAR completes.
func (q *Queries) GetRedundantMultipartUploads(ctx context.Context, arg GetRedundantMultipartUploadsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getRedundantMultipartUploads, arg.ObjectKey, arg.UploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var upload_id string
		if err := rows.Scan(&upload_id); err != nil {
			return nil, err
		}
		items = append(items, upload_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMultipartUpload = `-- name: InsertMultipartUpload :exec
INSERT INTO multipart_uploads (pending_closure_id, object_key, upload_id)
VALUES ($1, $2, $3)
`

type InsertMultipartUploadParams struct {
	PendingClosureID int64  `json:"pending_closure_id"`
	ObjectKey        string `json:"object_key"`
	UploadID         string `json:"upload_id"`
}

func (q *Queries) InsertMultipartUpload(ctx context.Context, arg InsertMultipartUploadParams) error {
	_, err := q.db.Exec(ctx, insertMultipartUpload, arg.PendingClosureID, arg.ObjectKey, arg.UploadID)
	return err
}

const insertPendingClosure = `-- name: InsertPendingClosure :one
INSERT INTO pending_closures (started_at, key)
VALUES (timezone('UTC', now()), $1)
RETURNING id, key, started_at
`

func (q *Queries) InsertPendingClosure(ctx context.Context, key string) (PendingClosure, error) {
	row := q.db.QueryRow(ctx, insertPendingClosure, key)
	var i PendingClosure
	err := row.Scan(&i.ID, &i.Key, &i.StartedAt)
	return i, err
}

type InsertPendingObjectsParams struct {
	PendingClosureID int64       `json:"pending_closure_id"`
	Key              string      `json:"key"`
	Refs             []string    `json:"refs"`
	Size             pgtype.Int8 `json:"size"`
}

const listPins = `-- name: ListPins :many
SELECT name, narinfo_key, store_path, created_at, updated_at
FROM pins
ORDER BY name
`

func (q *Queries) ListPins(ctx context.Context) ([]Pin, error) {
	rows, err := q.db.Query(ctx, listPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pin
	for rows.Next() {
		var i Pin
		if err := rows.Scan(
			&i.Name,
			&i.NarinfoKey,
			&i.StorePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObjectsForDeletion = `-- name: LockObjectsForDeletion :many
SELECT o.key
FROM objects AS o
WHERE o.deleted_at IS NOT NULL
  AND o.deleted_at <= $1::timestamp
  AND o.key > $2::varchar
  AND NOT EXISTS (SELECT 1 FROM pending_objects AS po WHERE po.key = o.key)
ORDER BY o.key
LIMIT $3
FOR UPDATE OF o
`

type LockObjectsForDeletionParams struct {
	Cutoff     pgtype.Timestamp `json:"cutoff"`
	AfterKey   string           `json:"after_key"`
	LimitCount int32            `json:"limit_count"`
}

// Run inside a transaction that stays open while the batch is deleted from
// S3. Keys referenced by any pending closure are excluded; see GetLiveObjects
// for the other half of the handshake.
func (q *Queries) LockObjectsForDeletion(ctx context.Context, arg LockObjectsForDeletionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, lockObjectsForDeletion, arg.Cutoff, arg.AfterKey, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleObjects = `-- name: MarkStaleObjects :execrows
WITH RECURSIVE ct AS (
    SELECT timezone('UTC', now()) AS now
),
closure_reach AS (
    -- Start with all closure keys
    SELECT o.key, o.refs
    FROM objects o
    INNER JOIN closures c ON o.key = c.key
    UNION
    -- Recursively add all referenced objects
    SELECT o.key, o.refs
    FROM objects o
    INNER JOIN closure_reach cr ON o.key = ANY(cr.refs)
),
reachable_objects AS (
    SELECT DISTINCT key FROM closure_reach
),
stale_objects AS (
    SELECT o.key
    FROM objects AS o, ct
    WHERE
        NOT EXISTS (
            SELECT 1
            FROM reachable_objects ro
            WHERE ro.key = o.key
        )
        AND NOT EXISTS (
            SELECT 1
            FROM pending_objects AS po
            WHERE po.key = o.key
        )
        AND o.deleted_at IS NULL
)
UPDATE objects
SET deleted_at = ct.now
FROM stale_objects, ct
WHERE objects.key = stale_objects.key
`

// Find all objects reachable from any closure
func (q *Queries) MarkStaleObjects(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleObjects)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerCompletedObject = `-- name: RegisterCompletedObject :exec
INSERT INTO objects (key, refs, size)
VALUES ($1, $2::varchar [], $3)
ON CONFLICT (key) DO UPDATE SET
    refs = (
        SELECT ARRAY(
            SELECT DISTINCT unnest(objects.refs || excluded.refs)
        )
    ),
    size = coalesce(objects.size, excluded.size),
    deleted_at = NULL
`

type RegisterCompletedObjectParams struct {
	Key  string      `json:"key"`
	Refs []string    `json:"refs"`
	Size pgtype.Int8 `json:"size"`
}

// Record an object as soon as its upload completes so later closures don't
// re-offer it if this closure never commits. Conflict handling matches
// commit_pending_closure: merge refs, keep a known size, resurrect tombstones.
func (q *Queries) RegisterCompletedObject(ctx context.Context, arg RegisterCompletedObjectParams) error {
	_, err := q.db.Exec(ctx, registerCompletedObject, arg.Key, arg.Refs, arg.Size)
	return err
}

const upsertPin = `-- name: UpsertPin :exec
INSERT INTO pins (name, narinfo_key, store_path, created_at, updated_at)
VALUES ($1, $2, $3, timezone('UTC', now()), timezone('UTC', now()))
ON CONFLICT (name) DO UPDATE SET
    narinfo_key = EXCLUDED.narinfo_key,
    store_path = EXCLUDED.store_path,
    updated_at = timezone('UTC', now())
`

type UpsertPinParams struct {
	Name       string `json:"name"`
	NarinfoKey string `json:"narinfo_key"`
	StorePath  string `json:"store_path"`
}

// Create or update a pin. Updates the narinfo_key, store_path, and updated_at if the pin already exists.
func (q *Queries) UpsertPin(ctx context.Context, arg UpsertPinParams) error {
	_, err := q.db.Exec(ctx, upsertPin, arg.Name, arg.NarinfoKey, arg.StorePath)
	return err
}
